Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
Checking C20250110163605.bin
Error for checking ./raw_data/C20250110163605.bin: Command '['python3', './check_data.py', './raw_data/C20250110163605.bin']' returned non-zero exit status 1.
